# Generated by Django 5.1.7 on 2025-04-01 16:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='tenant_photos/', verbose_name='photo')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('address', models.CharField(max_length=100, verbose_name='address')),
                ('mobile', models.CharField(max_length=15, verbose_name='mobile')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('profession', models.CharField(blank=True, max_length=100, verbose_name='profession')),
                ('house_name', models.CharField(default='Unknown', max_length=100, verbose_name='house name')),
                ('flat_number', models.CharField(max_length=10, verbose_name='flat number')),
                ('room_number', models.CharField(max_length=10, verbose_name='room number')),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='rent amount')),
                ('rent_start_date', models.DateField(blank=True, null=True, verbose_name='rent start date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
