# Generated by Django 5.1.7 on 2025-04-15 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='house_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='house name'),
        ),
    ]
