# Generated by Django 5.1.7 on 2025-05-07 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_alter_tenant_house_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='rent_start_date',
            field=models.CharField(blank=True, help_text='Format: YYYY-MM-DD', max_length=10, null=True, verbose_name='rent start date'),
        ),
    ]
