# Generated by Django 5.1.7 on 2025-07-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_alter_tenant_rent_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='pan_or_vat_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='PAN or VAT Number'),
        ),
    ]
