# Generated by Django 5.1.7 on 2025-04-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_passwordresetotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='system_logo/')),
            ],
            options={
                'verbose_name': 'system logo',
                'verbose_name_plural': 'system logos',
                'ordering': ['-created_at'],
            },
        ),
    ]
