# Generated by Django 5.1.7 on 2025-03-30 16:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_alter_tenant_address_alter_tenant_mobile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentInvoice',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('rent_month', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('tenant_name', models.CharField(max_length=100)),
                ('house_number', models.CharField(max_length=20)),
                ('flat_number', models.CharField(blank=True, max_length=20, null=True)),
                ('room_no', models.CharField(max_length=20)),
                ('building_name', models.CharField(max_length=100)),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('parking_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('electricity_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('security_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('account_name', models.CharField(blank=True, max_length=100, null=True)),
                ('owner_signature', models.CharField(blank=True, max_length=100, null=True)),
                ('tenant_signature', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'rent invoice',
                'verbose_name_plural': 'rent invoices',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('invoice_number', models.CharField(max_length=20, unique=True, verbose_name='invoice number')),
                ('date_issued', models.DateField(auto_now_add=True, verbose_name='date issued')),
                ('date_due', models.DateField(blank=True, null=True, verbose_name='date due')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='total amount')),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('overdue', 'Overdue')], default='unpaid', max_length=20, verbose_name='status')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_invoices', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'invoice',
                'verbose_name_plural': 'invoices',
                'ordering': ['-date_issued'],
            },
        ),
    ]
