# Generated by Django 5.1.7 on 2025-04-29 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_invoice_drinking_water_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='pan_or_vat_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
