# Generated by Django 5.1.7 on 2025-07-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_alter_feedback_attachment_alter_feedback_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-created_at'], 'verbose_name': 'प्रतिक्रिया', 'verbose_name_plural': 'प्रतिक्रियाहरू'},
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='feedback_date',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='anonymous',
            field=models.BooleanField(default=False, verbose_name='गोप्य राख्नुहोस्'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='feedback_attachments/', verbose_name='संलग्न फाइल'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_text',
            field=models.TextField(verbose_name='प्रतिक्रिया'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.CharField(choices=[('excellent', 'उत्कृष्ट'), ('good', 'राम्रो'), ('poor', 'नराम्रो')], max_length=20, verbose_name='रेटिङ'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('pending', 'पेन्डिङ'), ('solved', 'समाधान'), ('closed', 'बन्द')], default='pending', max_length=20, verbose_name='स्थिति'),
        ),
    ]
