# Generated by Django 5.1.7 on 2025-07-25 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_alter_feedback_options_remove_feedback_feedback_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-created_at'], 'verbose_name': 'Feedback', 'verbose_name_plural': 'Feedbacks'},
        ),
        migrations.AlterField(
            model_name='feedback',
            name='anonymous',
            field=models.BooleanField(default=False, verbose_name='Anonymous'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='feedback_attachments/', verbose_name='Attachment'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_text',
            field=models.TextField(verbose_name='Feedback'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('poor', 'Poor')], max_length=20, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('solved', 'Solved'), ('closed', 'Closed')], default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
